# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20170330_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
