# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_topic_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
